practice-for-ch-rails-music-app-long-practice-main/music_app/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # resources :bands

  resources :users, only: [:create, :new, :show]
  resource :session, only: [:new, :create, :destroy]
end

practice-for-ch-rails-music-app-long-practice-main/music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

practice-for-ch-rails-music-app-long-practice-main/music_app/app/models/band.rb
class Band < ApplicationRecord
    validates :name, presence: true, uniqueness: true
end

practice-for-ch-rails-music-app-long-practice-main/music_app/app/models/user.rb
class User < ApplicationRecord
    validates :email, presence: true, uniqueness: true
    validates :session_token, presence: true, uniqueness: true
    validates :password_digest, presence: true
    # validates :password, allow_nil: true
    before_validation :ensure_session_token

    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)

        if user && user.is_password?(password)
            return user            
        else
            return nil
        end
    end

    attr_reader :password

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        bcrypt_obj = BCrypt::Password.new(self.password_digest)
        bcrypt_obj.is_password?(password)
    end



    def reset_session_token!
        self.session_token = generate_unique_session_token
        self.save!
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= generate_unique_session_token
    end

    private

    def generate_unique_session_token
        loop do
            token = SecureRandom::urlsafe_base64(16)
            return token unless User.exists?(session_token: token)
        end
    end
end

practice-for-ch-rails-music-app-long-practice-main/music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session
    helper_method :current_user, :logged_in?
    
    def current_user
        session[:session_token]
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def logged_in?
        !!current_user
    end

    def login!(user)
        session[:session_token] = user.reset_session_token!
    end
end

practice-for-ch-rails-music-app-long-practice-main/music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        @user = User.new
        render :new
    end

    
    def create
        incoming_username = params[:user][:username]
        incoming_password = params[:user][:password]
        @user = User.find_by_credentials(incoming_username, incoming_password)

        if @user
            login!(@user) # session[:session_token] = @user.reset_session_token
            redirect_to users_url
        else
            render :new 
        end
    end
    

    def destroy

    end
end

practice-for-ch-rails-music-app-long-practice-main/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
        render :new
    end
    
    def create
        @user = User.new(user_params)

        if @user.save
            login!(@user)
            redirect_to new_session_url
        else
            render :new
        end
    end

    def show
        @user = User.find(params[:id])
        render :show
    end
   
    private 

    def user_params
        params.require(:user).permit(:email, :password)
    end
end

practice-for-ch-rails-music-app-long-practice-main/music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

practice-for-ch-rails-music-app-long-practice-main/music_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

practice-for-ch-rails-music-app-long-practice-main/music_app/app/helpers/users_helper.rb
module UsersHelper
end

practice-for-ch-rails-music-app-long-practice-main/music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <% if logged_in? %>
      <h2><%= current_user.email %></h2>
      <form action="<%= session_url %>" method="POST">
        <input type="hidden" name="_method" method="DELETE">
          <button>Logout</button>
      </form>

    <% else %>
      <a href="<%= new_session_url %>">Log in here</a>
      <a href="<%= new_user_url %>">Create new user</a>
    <% end %>

    <%= yield %>
  </body>
</html>

practice-for-ch-rails-music-app-long-practice-main/music_app/app/views/users/new.html.erb
<h1>Create an Account</h1>

<form action=" <%= users_url %>" method="POST">
    <input type="text" name="user[email]" value="">
    <input type="password" name="user[password]" value="">
    <button>Submit</button>
</form>

practice-for-ch-rails-music-app-long-practice-main/music_app/app/views/users/show.html.erb
<h1><%= @user.email %></h1>